CREATE SCHEMA IF NOT EXISTS MEMORY;

SET search_path TO MEMORY, public;

-- ALTER USER postgres WITH PASSWORD '**********';

create extension if not exists vector;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE EXTENSION IF NOT EXISTS "pg_trgm";


CREATE TABLE MEMORY.USERS (
    user_id UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
    name VARCHAR(255),
    email VARCHAR(255),
    password TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE MEMORY.SESSIONS (
    session_id UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
    user_id UUID NOT NULL,
    session_name VARCHAR(60),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    terminated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE MEMORY.CHATS (
    chat_id UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
    session_id UUID NOT NULL,
    sender TEXT NOT NULL CHECK (sender IN ('user', 'assistant')),
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


-- SELECT * FROM MEMORY.USERS;
-- SELECT * FROM MEMORY.SESSIONS;
-- SELECT * FROM MEMORY.CHATS;

